export const COLOR_NAMES = [
    "Violet",
    "Indigo",
    "Blue",
    "Green",
    "Yellow",
    "Orange",
    "Red",
    "AliceBlue",
    "AntiqueWhite",
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "BlanchedAlmond",
    "BlueViolet",
    "Brown",
    "BurlyWood",
    "CadetBlue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "CornflowerBlue",
    "Cornsilk",
    "Crimson",
    "Cyan",
    "DarkBlue",
    "DarkCyan",
    "DarkGoldenRod",
    "DarkGray",
    "DarkGrey",
    "DarkGreen",
    "DarkKhaki",
    "DarkMagenta",
    "DarkOliveGreen",
    "DarkOrange",
    "DarkOrchid",
    "DarkRed",
    "DarkSalmon",
    "DarkSeaGreen",
    "DarkSlateBlue",
    "DarkSlateGray",
    "DarkSlateGrey",
    "DarkTurquoise",
    "DarkViolet",
    "DeepPink",
    "DeepSkyBlue",
    "DimGray",
    "DimGrey",
    "DodgerBlue",
    "FireBrick",
    "FloralWhite",
    "ForestGreen",
    "Fuchsia",
    "Gainsboro",
    "GhostWhite",
    "Gold",
    "GoldenRod",
    "Gray",
    "Grey",
    "GreenYellow",
    "HoneyDew",
    "HotPink",
    "IndianRed",
    "Ivory",
    "Khaki",
    "Lavender",
    "LavenderBlush",
    "LawnGreen",
    "LemonChiffon",
    "LightBlue",
    "LightCoral",
    "LightCyan",
    "LightGoldenRodYellow",
    "LightGray",
    "LightGrey",
    "LightGreen",
    "LightPink",
    "LightSalmon",
    "LightSeaGreen",
    "LightSkyBlue",
    "LightSlateGray",
    "LightSlateGrey",
    "LightSteelBlue",
    "LightYellow",
    "Lime",
    "LimeGreen",
    "Linen",
    "Magenta",
    "Maroon",
    "MediumAquaMarine",
    "MediumBlue",
    "MediumOrchid",
    "MediumPurple",
    "MediumSeaGreen",
    "MediumSlateBlue",
    "MediumSpringGreen",
    "MediumTurquoise",
    "MediumVioletRed",
    "MidnightBlue",
    "MintCream",
    "MistyRose",
    "Moccasin",
    "NavajoWhite",
    "Navy",
    "OldLace",
    "Olive",
    "OliveDrab",
    "OrangeRed",
    "Orchid",
    "PaleGoldenRod",
    "PaleGreen",
    "PaleTurquoise",
    "PaleVioletRed",
    "PapayaWhip",
    "PeachPuff",
    "Peru",
    "Pink",
    "Plum",
    "PowderBlue",
    "Purple",
    "RebeccaPurple",
    "RosyBrown",
    "RoyalBlue",
    "SaddleBrown",
    "Salmon",
    "SandyBrown",
    "SeaGreen",
    "SeaShell",
    "Sienna",
    "Silver",
    "SkyBlue",
    "SlateBlue",
    "SlateGray",
    "SlateGrey",
    "Snow",
    "SpringGreen",
    "SteelBlue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Wheat",
    "White",
    "WhiteSmoke",
    "YellowGreen",
  ];

export const numberArrayCal = function() {
    const numberArr = [];
      for (let i = 0; i <= 40; i++) {
        numberArr.push(i.toString());
      }
      return numberArr;
}

export interface AlphabetData {
    meaning: string;
    emoji: string;
}

export const ALPHABET_DATA: Record<string, AlphabetData> = {
    'a': { meaning: 'A for Apple', emoji: '🍎' },
    'b': { meaning: 'B for Ball', emoji: '⚽' },
    'c': { meaning: 'C for Cat', emoji: '🐱' },
    'd': { meaning: 'D for Dog', emoji: '🐕' },
    'e': { meaning: 'E for Elephant', emoji: '🐘' },
    'f': { meaning: 'F for Fish', emoji: '🐟' },
    'g': { meaning: 'G for Grapes', emoji: '🍇' },
    'h': { meaning: 'H for Hat', emoji: '🎩' },
    'i': { meaning: 'I for Ice cream', emoji: '🍦' },
    'j': { meaning: 'J for Jug', emoji: '🫗' },
    'k': { meaning: 'K for Kite', emoji: '🪁' },
    'l': { meaning: 'L for Lion', emoji: '🦁' },
    'm': { meaning: 'M for Monkey', emoji: '🐵' },
    'n': { meaning: 'N for Nest', emoji: '🪺' },
    'o': { meaning: 'O for Orange', emoji: '🍊' },
    'p': { meaning: 'P for Parrot', emoji: '🦜' },
    'q': { meaning: 'Q for Queen', emoji: '👸' },
    'r': { meaning: 'R for Rabbit', emoji: '🐰' },
    's': { meaning: 'S for Sun', emoji: '☀️' },
    't': { meaning: 'T for Tiger', emoji: '🐯' },
    'u': { meaning: 'U for Umbrella', emoji: '☂️' },
    'v': { meaning: 'V for Van', emoji: '🚐' },
    'w': { meaning: 'W for Watch', emoji: '⌚' },
    'x': { meaning: 'X for Xylophone', emoji: '🎵' },
    'y': { meaning: 'Y for Yak', emoji: '🐃' },
    'z': { meaning: 'Z for Zebra', emoji: '🦓' }
};

// Legacy export for backward compatibility
export const ALPHABET_MEANINGS: Record<string, string> = Object.fromEntries(
    Object.entries(ALPHABET_DATA).map(([key, value]) => [key, value.meaning])
);

export const ARRAY_LIST = {
    alphabet: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
    'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
    month: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    transport: ['Bus', 'Car', 'Airplane', 'Boat', 'Train', 'Helicopter', 'Van', 'Bicycle', 'Tractor', 'Motorcycle', 'Ambulance', 'Crane', 'Autorikshaw', 'Metro', 'Scooty', 'Scooter', 'Ship', 'Jcb' ],
    fruit: ['Apple', 'Apricot', 'Avocado', 'Banana', 'Cherry', 'Dragonfruit', 'Fig', 'Grapes', 'Guava', 'Kiwi', 'Lemon', 'Mango', 'Orange', 'Papaya', 'Pineapple', 'Pomegranate', 'Raspberry', 'Strawberry', 'Watermelon']
}